export const PURGE_AUTH = 'logOut'
export const SET_AUTH = 'setUser'
export const SET_ERROR = 'setError'
export const SET_LOGIN_ERROR = 'setLoginError'
export const SET_UPDATE_USER = 'setUpdateUser'
export const SET_SARRES = 'setSarres'
export const SET_PRODUCT_BY_ID = 'setProductById'
export const SET_PRODUCT_TO_CART = 'addProductToCart'